FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY tsconfig.base.json ./
COPY packages ./packages
COPY apps/api ./apps/api

RUN npm ci

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma

EXPOSE 4000

CMD ["npx", "tsx", "apps/api/src/index.ts"]